name: EmptyCases
version: '${version}'
main: smp.plugin.GooseMooz.EmptyCases
api-version: '1.20'
commands:
  emptycases:
    description: "Opens EmptyCases GUI"
    usage: "/emptycases"
    aliases: emptycases